AllCops:
  UseCache: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
Metrics:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
